apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: castai-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: castai-app
  template:
    metadata:
      labels:
        app: castai-app
    spec:
      serviceAccountName: target-registrar-sa
      containers:
      - name: castai-container
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: {{ .Values.awsRegion | quote }}
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: castai-secrets
              key: apiKey
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: castai-secrets
              key: clusterId
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
