apiVersion: v1
kind: Secret
metadata:
  name: castai-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  apiKey: {{ .Values.apiKey | b64enc }}
  clusterId: {{ .Values.clusterId | b64enc }}
